#include "Headers/cityBuilder.hpp"
#include <stdlib.h>
#include <time.h>

using namespace std;




City::City(int s) {
    size = s;
    this->cityArray;
}


void City::createCity() {
    srand(time(NULL));
    int array[size][size];  
    for(int i = 0; i < size; i++) {
        for(int j = 0; j < size; j++) {
            array[i][j] = rand()%10;
        }
    }

    for(int i = 0; i < size; i++) {
        cityArray[i] = array[i];
    }

    return;
}


void City::printCity() {
    cout << "|";
    for(int i = 0; i < size; i++){
        cout << "-";
    }
    cout << "|" << endl;
    for(int i = 0; i < size; i++) {
        for(int j = 0; j < size; j++) {
            //cout << " " << cityArray[i][j] << " ";
        }
        //cout << " " << cityArray[i][j] << " ";
        cout << "|" << endl;
    }
    for(int i = 0; i < size; i++){
        cout << "-";
    }
    cout << "|" << endl;
    return;
}


//  TODO 
// Need to figure out whether the parent class is cityBuilder or if it is menuEntry. menuEntry comes first so I suspect that would be the one.
// City::City(int s) {
//     size = s*s;
// }

// void City::createCity() {
//     srand (time(NULL));
//     int array[size];

//     //      This is the first iteration of this process. Ideally I would eventually like to make
//     //      a heatmap with hot points being tall towers. The points would then decay outward
//     //      creating a 3d representation of the height of the buildings on a 2d map which
//     //      maps out their location. This would give me a great start for making cities of all
//     //      different kinds generated by random seeds.
//     for(int i = 0; i < size; i++) {
//         if((rand()%3) == 1) {
//             array[i] = 1;
//         }
//         else {
//             array[i] = 0;
//         }
//     }
//     cityArray = array;
    

//     cout << "New city has been generated." << endl;
// }

// void City::printCity(){
//     for(int i = 0; i < size; i++){
//         std::cout << "|  ";
//         for(int j = i*size; j < size; j++){
//             std::cout << " " << cityArray[j] << " "; 
//         }
//         std::cout << "  |" << std::endl;
//     }

//     return;
// }

